controller_frequency: 1.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:
   max_vel_x: 0.5  # m/s
   min_vel_x: -0.5
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_vel_theta: 2.26  # rad/s
   min_vel_theta: -2.26
   min_in_place_vel_theta: 0.25
   escape_vel: -0.1
   acc_lim_x: 1.5
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 1.2

   holonomic_robot: false
   yaw_goal_tolerance: 0.1 # about 6 degrees
   xy_goal_tolerance: 0.1  # 10 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 32.0  # 0.9 -> 32.0
   gdist_scale: 20.0  # 0.6 -> 20.0
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.02  # 0.1 -> 0.02
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 4.0  # 1.0 -> 4.0 by lyy
   sim_granularity: 0.025  # sim granularity is the step size to take between points on a trajectory
   angular_sim_granularity: 0.025
   vx_samples: 20  # 8 -> 20 by lyy
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 40  # 20 -> 40 by lyy
   dwa: true
   simple_attractor: false
